modLoader="javafml"
loaderVersion="[4,)"
license="GNU Lesser General Public License version 2.1 (LGPLv2.1)"

[[mods]]
modId="mob_execution"
version="0.0.1"
displayName="Mob Execution"
displayURL="https://myshuaibi.dpdns.org/"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="myshuaibi"
description="None"

# Start of user code block mod configuration
# End of user code block mod configuration


# Start of user code block custom mixins
# End of user code block custom mixins

[[dependencies.mob_execution]]
    modId="neoforge"
    type="required"
    versionRange="[21.1.190,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.mob_execution]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1]"
    ordering="AFTER"
    side="BOTH"


[[dependencies.mob_execution]]
    modId="jei"
    type="optional"
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"


# Start of user code block dependencies configuration
# End of user code block dependencies configuration